Add rm tests
fire-breathing-rubber-lemons/cs207-FinalProject pull request #40
Opened 2019-12-07 21:35 UTC by HaydenSansum

2019-12-08 00:12 UTC, catharinewu submitted a review, later dismissed

2019-12-08 03:22 UTC, edjah submitted a review, later dismissed
lgtm thanks

2019-12-09 05:01 UTC, edjah requested changes

2019-12-09 05:01 UTC, edjah commented on pyad/tests/test_reverse.py
> +    assert t2.children[0][0] == -t2.value
Can you use `.grad` to compare derivatives instead of checking `.children`

2019-12-09 17:41 UTC, edjah approved these changes

2019-12-09 17:41 UTC, merged